### ISSUE TITLE
[HRP-L 1.0] Haven distress cant be turned off

### ISSUE THREAD

**Issue by CurePindal** [zorkind/HRP-Light#49]
**Vanilla / HRP Light**
 HRP Light,  MP EU-west server

**Client Version**
HRP Light 1.0

**Describe the bug**
The distress call on the haven can be turned on but wont turn off again.

**To Reproduce**
1. click distress button
2. button is green
3. no more further clicks recognized - button stays green, distress stays active

**Expected behavior**
Button switches distress on/off

**Comment by GTink911** [comment]
Fixed in HRP-L 1.1. (Does this technically mean a average response time of a year and a half?)
